/*const edad = Number(prompt("Ingrese su edad"));
if (edad > 18) {
	alert("Es mayor de edad");
} else if (edad > 0) {
	alert("Es menor de edad");
} else {
	alert("Edad incorrecta");
}

const cantidad = Number(prompt("¿Cuántos números desea sumar?"));

let sumatoria = 0;
for (let index = 1; index <= cantidad; index++) {
    const numeroAsumar = Number(prompt("Ingrese un número a sumar"));
    sumatoria = sumatoria + numeroAsumar;
  }

  alert(sumatoria)



  let totalApagar = 0;

  const cantidadProductos = Number(prompt("¿Cuántos productos desea comprar?"));
  
  for (let index = 1; index <= cantidadProductos; index++) {
      const nombre = prompt("¿Qué producto desea llevar?");
      const cantidad = Number(prompt("¿Cuántas unidades?"));
      const precio = Number(prompt("¿Cuánto sale cada unidad?"));
      const subtotal = cantidad * precio;
      totalApagar += subtotal;
  }
  
  console.log("El total a pagar es: " + totalApagar);
  
  alert(totalApagar)*/